# Generated by Django 2.2 on 2019-04-25 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Miscellaneous',
            new_name='Misc',
        ),
    ]
